version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: app-redis
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    restart: always

  flask_app:
    build:
      context: my_flask_app
      dockerfile: Dockerfile
    container_name: app-flask
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "10000:5000"
    depends_on:
      - redis
    restart: always

  celery_app:
    build:
      context: my_celery_app
      dockerfile: Dockerfile
    container_name: app-celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always